# Generated by Django 3.2.19 on 2023-06-27 12:25

import EasyDoc_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('poste_role', models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipp', models.CharField(max_length=12)),
                ('cin_assurant', models.CharField(max_length=12)),
                ('ordonnance', models.FileField(upload_to='ordonnance/', validators=[EasyDoc_app.models.validate_file_extension])),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('tele', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('poste_role', models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20)),
                ('service_medecin', models.CharField(choices=[('medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite')], max_length=20)),
                ('inpe', models.CharField(max_length=10)),
                ('responsable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('tele', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('poste_role', models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20)),
                ('service_role', models.CharField(choices=[('SAA', 'SAA')], max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Biologie',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EasyDoc_app.consultation')),
                ('bonBio', models.FileField(upload_to='bonBio/', validators=[EasyDoc_app.models.validate_file_extension])),
                ('facture', models.FileField(upload_to='facture/', validators=[EasyDoc_app.models.validate_file_extension])),
            ],
            bases=('EasyDoc_app.consultation',),
        ),
        migrations.CreateModel(
            name='Hospitalisation',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EasyDoc_app.consultation')),
                ('dateSortie', models.CharField(max_length=100)),
                ('billetHospitalisation', models.FileField(upload_to='billet_hosp/', validators=[EasyDoc_app.models.validate_file_extension])),
                ('facture', models.FileField(upload_to='facture/', validators=[EasyDoc_app.models.validate_file_extension])),
            ],
            bases=('EasyDoc_app.consultation',),
        ),
        migrations.CreateModel(
            name='Radiologie',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='EasyDoc_app.consultation')),
                ('bonRadio', models.FileField(upload_to='bonRadio/', validators=[EasyDoc_app.models.validate_file_extension])),
                ('facture', models.FileField(upload_to='facture/', validators=[EasyDoc_app.models.validate_file_extension])),
            ],
            bases=('EasyDoc_app.consultation',),
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinAssure', models.CharField(max_length=12)),
                ('ipp', models.CharField(max_length=12)),
                ('cnss', models.CharField(max_length=12)),
                ('phCIN', models.FileField(upload_to='phCIN/', validators=[EasyDoc_app.models.validate_file_extension])),
                ('phCNSS', models.FileField(upload_to='phCNSS/', validators=[EasyDoc_app.models.validate_file_extension])),
                ('consultations', models.ManyToManyField(to='EasyDoc_app.Consultation')),
            ],
        ),
    ]
