# Generated by Django 3.2.19 on 2023-06-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0002_auto_20230627_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentification',
            name='poste_role',
        ),
        migrations.AddField(
            model_name='authentification',
            name='service',
            field=models.CharField(choices=[('medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite'), ('SAA', 'SAA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='poste_role',
            field=models.CharField(choices=[('medecin', 'medecin'), ('technicien', 'technicien')], max_length=20),
        ),
    ]
