# Generated by Django 3.2.19 on 2023-06-27 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0003_auto_20230627_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentification',
            name='service',
            field=models.CharField(choices=[('medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite'), ('SAA', 'SAA'), ('admin', 'admin')], max_length=20, null=True),
        ),
    ]
