# Generated by Django 3.2.19 on 2023-07-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0004_alter_authentification_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentification',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
