# Generated by Django 3.2.19 on 2023-07-01 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0006_remove_dossiermedical_consultations'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='service',
            field=models.CharField(choices=[('Medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite'), ('centreDC', 'CentreDC')], default=('Medecine', 'Medecine'), max_length=20),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='phCIN',
            field=models.FileField(upload_to='phCIN/'),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='phCNSS',
            field=models.FileField(upload_to='phCNSS/'),
        ),
    ]
