# Generated by Django 3.2.19 on 2023-07-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0007_auto_20230702_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='service',
            field=models.CharField(choices=[('Medecine', 'Medecine'), ('chirurgie', 'Chirurgie'), ('pediaterie', 'Pediaterie'), ('maternite', 'Maternite'), ('centreDC', 'CentreDC'), ('Radiologie', 'Radiologie'), ('Biologie', 'Biologie')], default=('Medecine', 'Medecine'), max_length=20),
        ),
    ]
