# Generated by Django 3.2.19 on 2023-07-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0009_alter_consultation_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dossiermedical',
            unique_together={('cinAssure', 'ipp')},
        ),
    ]
