# Generated by Django 3.2.19 on 2023-07-03 14:46

import EasyDoc_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0011_auto_20230703_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='dpc',
            field=models.FileField(null=True, upload_to='facture/', validators=[EasyDoc_app.models.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='pli_confidentiel',
            field=models.FileField(null=True, upload_to='facture/', validators=[EasyDoc_app.models.validate_file_extension]),
        ),
    ]
