# Generated by Django 3.2.19 on 2023-07-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0012_auto_20230703_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='action',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Radiologie', 'Radiologie'), ('Biologie', 'Biologie'), ('Hospitalisation', 'Hospitalisation')], default=('Consultation', 'Consultation'), max_length=50),
        ),
    ]
