# Generated by Django 3.2.19 on 2023-07-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0013_consultation_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='ordonnance',
            field=models.FileField(upload_to='ordonnance/'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='billetHospitalisation',
            field=models.FileField(upload_to='billet_hosp/'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='dpc',
            field=models.FileField(null=True, upload_to='facture/'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='facture',
            field=models.FileField(upload_to='facture/'),
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='pli_confidentiel',
            field=models.FileField(null=True, upload_to='facture/'),
        ),
    ]
