# Generated by Django 3.2.19 on 2023-07-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0014_auto_20230703_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='imprime',
            field=models.BooleanField(default=False),
        ),
    ]
