# Generated by Django 3.2.19 on 2023-07-04 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0015_consultation_imprime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='radiologie',
            name='bonRadio',
            field=models.FileField(upload_to='bonRadio/'),
        ),
        migrations.AlterField(
            model_name='radiologie',
            name='facture',
            field=models.FileField(upload_to='facture/'),
        ),
    ]
