# Generated by Django 3.2.19 on 2023-07-04 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0016_auto_20230705_0055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
