# Generated by Django 3.2.19 on 2023-07-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EasyDoc_app', '0018_alter_medecin_service_medecin'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='medecin',
            field=models.CharField(default='0000000', max_length=100),
        ),
    ]
